spring:
  application:
    name: meamar-marketplace
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    oauth2:
      client:
        registration:
          replit:
            client-id: ${REPLIT_CLIENT_ID:}
            client-secret: ${REPLIT_CLIENT_SECRET:}
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/v1/auth/callback"
        provider:
          replit:
            issuer-uri: ${ISSUER_URL:}

server:
  port: 8080
  servlet:
    context-path: /api/v1

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours
  
  storage:
    gcs:
      bucket-id: ${DEFAULT_OBJECT_STORAGE_BUCKET_ID}
      project-id: ${GCS_PROJECT_ID:meamar}
  
  stripe:
    api-key: ${STRIPE_SECRET_KEY:}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

logging:
  level:
    com.meamar: INFO
    org.springframework.security: INFO
    # For development, you can enable DEBUG:
    # com.meamar: DEBUG
    # org.springframework.security: DEBUG
